export const USER_LOCATION_RESPONSES = {
    //STATE
    USER_STATE_LOCATION_NOT_FOUND: {
        status: 404,
        message: 'USER STATE LOCATION NOT FOUND',
    },
    USER_STATE_LOCATION_CREATION_FAILED: {
        status: 500,
        message: 'USER STATE LOCATION COULD NOT BE CREATED',
    },
    USER_STATE_LOCATION_CREATED: {
        status: 201,
        message: 'USER STATE LOCATION CREATED SUCCESSFULLY',
    },
    CANNOT_UPDATE_USER_STATE_LOCATION: {
        status: 500,
        message: 'USER STATE LOCATION UPDATE FAILED',
    },
    USER_STATE_LOCATION_UPDATED: {
        status: 201,
        message: 'USER STATE LOCATION UPDATED SUCCESSFULLY',
    },
    CANNOT_DELETE_USER_STATE_LOCATION: {
        status: 500,
        message: 'CANNOT DELETE USER STATE LOCATION',
    },
    DELETED_USER_STATE_LOCATION: {
        status: 201,
        message: 'USER STATE LOCATION DELETED SUCCESSFULLY',
    },

    //DISTRICT
    USER_DISTRICT_LOCATION_NOT_FOUND: {
        status: 404,
        message: 'USER DISTRICT LOCATION NOT FOUND',
    },
    USER_DISTRICT_LOCATION_CREATION_FAILED: {
        status: 500,
        message: 'USER DISTRICT LOCATION COULD NOT BE CREATED',
    },
    USER_DISTRICT_LOCATION_CREATED: {
        status: 201,
        message: 'USER DISTRICT LOCATION CREATED SUCCESSFULLY',
    },
    CANNOT_UPDATE_USER_DISTRICT_LOCATION: {
        status: 500,
        message: 'USER DISTRICT LOCATION UPDATE FAILED',
    },
    USER_DISTRICT_LOCATION_UPDATED: {
        status: 201,
        message: 'USER DISTRICT LOCATION UPDATED SUCCESSFULLY',
    },
    CANNOT_DELETE_USER_DISTRICT_LOCATION: {
        status: 500,
        message: 'CANNOT DELETE USER DISTRICT LOCATION',
    },
    DELETED_USER_DISTRICT_LOCATION: {
        status: 201,
        message: 'USER DISTRICT LOCATION DELETED SUCCESSFULLY',
    },

    //CITY
    USER_CITY_LOCATION_NOT_FOUND: {
        status: 404,
        message: 'USER CITY LOCATION NOT FOUND',
    },
    USER_CITY_LOCATION_CREATION_FAILED: {
        status: 500,
        message: 'USER LOCATION COULD NOT BE CREATED',
    },
    USER_CITY_LOCATION_CREATED: {
        status: 201,
        message: 'USER LOCATION CREATED SUCCESSFULLY',
    },
    CANNOT_UPDATE_USER_CITY_LOCATION: {
        status: 500,
        message: 'USER CITY LOCATION UPDATE FAILED',
    },
    USER_CITY_LOCATION_UPDATED: {
        status: 201,
        message: 'USER CITY LOCATION UPDATED SUCCESSFULLY',
    },
    CANNOT_DELETE_USER_CITY_LOCATION: {
        status: 500,
        message: 'CANNOT DELETE USER CITY LOCATION',
    },
    DELETED_USER_CITY_LOCATION: {
        status: 201,
        message: 'USER CITY LOCATION DELETED SUCCESSFULLY',
    },
};
